# WriterAgent - AI Writing Assistant for LibreOffice
# Copyright (c) 2026 KeithCu
#
# SPDX-License-Identifier: GPL-3.0-or-later
"""Tests for FizzBee installer asset matching and CLI detection."""

from __future__ import annotations

import os
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

from scripts.install_fizzbee import (
    find_cli_in_tree,
    is_fizzbee_cli,
    release_platform_token,
    select_release_asset,
)

_PROTO_STUB = """# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
from google.protobuf import descriptor as _descriptor
"""

_WRAPPER = "#!/bin/sh\nexec \"$0.real\" \"$@\"\n"


def test_release_platform_token_linux_x86():
    assert release_platform_token("Linux", "x86_64") == "linux_x86"
    assert release_platform_token("Linux", "amd64") == "linux_x86"
    assert release_platform_token("Linux", "aarch64") == "linux_arm"
    assert release_platform_token("Darwin", "arm64") == "macos_arm"
    assert release_platform_token("Darwin", "x86_64") == "macos_x86"


def test_select_release_asset_skips_source_and_wrong_arch():
    assets = [
        {"name": "Source code (tar.gz)", "browser_download_url": "s"},
        {"name": "fizzbee-v0.4.0-linux_arm.tar.gz", "browser_download_url": "arm"},
        {"name": "fizzbee-v0.4.0-linux_x86.tar.gz", "browser_download_url": "x86"},
        {"name": "fizzbee-v0.4.0-macos_arm.tar.gz", "browser_download_url": "mac"},
    ]
    picked = select_release_asset(assets, "linux_x86")
    assert picked is not None
    assert picked["browser_download_url"] == "x86"
    assert select_release_asset(assets, "windows_x86") is None


def test_is_fizzbee_cli_rejects_protobuf_stub(tmp_path: Path):
    stub = tmp_path / "fizzbee"
    stub.write_text(_PROTO_STUB)
    stub.chmod(0o755)
    assert is_fizzbee_cli(str(stub)) is False

    wrapper = tmp_path / "fizz"
    wrapper.write_text(_WRAPPER)
    wrapper.chmod(0o755)
    assert is_fizzbee_cli(str(wrapper)) is True

    # Basename must be fizzbee; write ELF next to wrapper under that name in a subdir.
    native = tmp_path / "bin"
    native.mkdir()
    native_cli = native / "fizzbee"
    native_cli.write_bytes(b"\x7fELF" + b"\x00" * 20)
    native_cli.chmod(0o755)
    assert is_fizzbee_cli(str(native_cli)) is True


def test_find_cli_in_tree_prefers_wrapper_over_proto_stub(tmp_path: Path):
    proto = tmp_path / "proto"
    proto.mkdir()
    stub = proto / "fizzbee"
    stub.write_text(_PROTO_STUB)
    stub.chmod(0o755)

    wrapper = tmp_path / "fizz"
    wrapper.write_text(_WRAPPER)
    wrapper.chmod(0o755)

    found = find_cli_in_tree(str(tmp_path))
    assert found is not None
    assert os.path.basename(found) == "fizz"
    assert found == str(wrapper)
